name: Auto merge em pull request na branch homologao-interno
on:
  pull_request:
    branches:
      - homologacao-interno
    types:
      - opened
jobs:
  merge_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Realizando merge
        env: 
          GH_TOKEN: ${{ secrets.token }}
        run: gh pr merge ${{ github.event.pull_request.number }} --squash
